// Auto-generated by: supabase gen types typescript --project-id rgdaiiglgrpcsidrcuzt --schema public
// Run `npm run db:types` to regenerate after schema changes.
// This placeholder will be overwritten once migrations are pushed.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: {
      audit_logs: {
        Row: {
          action: string;
          created_at: string;
          id: string;
          new_value: Json | null;
          previous_value: Json | null;
          record_id: string;
          table_name: string;
          user_id: string;
        };
        Insert: {
          action: string;
          created_at?: string;
          id?: string;
          new_value?: Json | null;
          previous_value?: Json | null;
          record_id: string;
          table_name: string;
          user_id: string;
        };
        Update: {
          action?: string;
          created_at?: string;
          id?: string;
          new_value?: Json | null;
          previous_value?: Json | null;
          record_id?: string;
          table_name?: string;
          user_id?: string;
        };
        Relationships: [];
      };
      countries: {
        Row: {
          base_currency: string;
          code: string;
          created_at: string;
          deleted_at: string | null;
          deleted_by: string | null;
          id: string;
          is_active: boolean;
          name: string;
          updated_at: string;
        };
        Insert: {
          base_currency: string;
          code: string;
          created_at?: string;
          deleted_at?: string | null;
          deleted_by?: string | null;
          id?: string;
          is_active?: boolean;
          name: string;
          updated_at?: string;
        };
        Update: {
          base_currency?: string;
          code?: string;
          created_at?: string;
          deleted_at?: string | null;
          deleted_by?: string | null;
          id?: string;
          is_active?: boolean;
          name?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'fk_countries_deleted_by';
            columns: ['deleted_by'];
            isOneToOne: false;
            referencedRelation: 'user_profiles';
            referencedColumns: ['id'];
          },
        ];
      };
      exchange_rates: {
        Row: {
          created_at: string;
          effective_date: string;
          from_currency: string;
          id: string;
          is_manual: boolean;
          overridden_by: string | null;
          rate: number;
          source: string | null;
          to_currency: string;
        };
        Insert: {
          created_at?: string;
          effective_date: string;
          from_currency: string;
          id?: string;
          is_manual?: boolean;
          overridden_by?: string | null;
          rate: number;
          source?: string | null;
          to_currency: string;
        };
        Update: {
          created_at?: string;
          effective_date?: string;
          from_currency?: string;
          id?: string;
          is_manual?: boolean;
          overridden_by?: string | null;
          rate?: number;
          source?: string | null;
          to_currency?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'exchange_rates_overridden_by_fkey';
            columns: ['overridden_by'];
            isOneToOne: false;
            referencedRelation: 'user_profiles';
            referencedColumns: ['id'];
          },
        ];
      };
      expense_categories: {
        Row: {
          created_at: string;
          deleted_at: string | null;
          deleted_by: string | null;
          id: string;
          is_active: boolean;
          name: string;
          parent_id: string | null;
          slug: string;
          sort_order: number;
          updated_at: string;
        };
        Insert: {
          created_at?: string;
          deleted_at?: string | null;
          deleted_by?: string | null;
          id?: string;
          is_active?: boolean;
          name: string;
          parent_id?: string | null;
          slug: string;
          sort_order?: number;
          updated_at?: string;
        };
        Update: {
          created_at?: string;
          deleted_at?: string | null;
          deleted_by?: string | null;
          id?: string;
          is_active?: boolean;
          name?: string;
          parent_id?: string | null;
          slug?: string;
          sort_order?: number;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'expense_categories_deleted_by_fkey';
            columns: ['deleted_by'];
            isOneToOne: false;
            referencedRelation: 'user_profiles';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'expense_categories_parent_id_fkey';
            columns: ['parent_id'];
            isOneToOne: false;
            referencedRelation: 'expense_categories';
            referencedColumns: ['id'];
          },
        ];
      };
      expense_records: {
        Row: {
          amount: number;
          amount_base: number;
          attachment_name: string | null;
          attachment_size_kb: number | null;
          attachment_url: string | null;
          category_id: string;
          created_at: string;
          created_by: string;
          currency: string;
          date: string;
          deleted_at: string | null;
          deleted_by: string | null;
          exchange_rate_used: number;
          id: string;
          is_recurring: boolean;
          notes: string | null;
          payment_method: string;
          property_id: string;
          recurring_id: string | null;
          room_id: string | null;
          status: string;
          updated_at: string;
          updated_by: string | null;
          vendor: string | null;
        };
        Insert: {
          amount: number;
          amount_base: number;
          attachment_name?: string | null;
          attachment_size_kb?: number | null;
          attachment_url?: string | null;
          category_id: string;
          created_at?: string;
          created_by: string;
          currency: string;
          date: string;
          deleted_at?: string | null;
          deleted_by?: string | null;
          exchange_rate_used: number;
          id?: string;
          is_recurring?: boolean;
          notes?: string | null;
          payment_method: string;
          property_id: string;
          recurring_id?: string | null;
          room_id?: string | null;
          status?: string;
          updated_at?: string;
          updated_by?: string | null;
          vendor?: string | null;
        };
        Update: {
          amount?: number;
          amount_base?: number;
          attachment_name?: string | null;
          attachment_size_kb?: number | null;
          attachment_url?: string | null;
          category_id?: string;
          created_at?: string;
          created_by?: string;
          currency?: string;
          date?: string;
          deleted_at?: string | null;
          deleted_by?: string | null;
          exchange_rate_used?: number;
          id?: string;
          is_recurring?: boolean;
          notes?: string | null;
          payment_method?: string;
          property_id?: string;
          recurring_id?: string | null;
          room_id?: string | null;
          status?: string;
          updated_at?: string;
          updated_by?: string | null;
          vendor?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: 'expense_records_category_id_fkey';
            columns: ['category_id'];
            isOneToOne: false;
            referencedRelation: 'expense_categories';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'expense_records_property_id_fkey';
            columns: ['property_id'];
            isOneToOne: false;
            referencedRelation: 'properties';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'fk_expense_records_recurring';
            columns: ['recurring_id'];
            isOneToOne: false;
            referencedRelation: 'recurring_expenses';
            referencedColumns: ['id'];
          },
        ];
      };
      financial_year_settings: {
        Row: {
          created_at: string;
          deleted_at: string | null;
          deleted_by: string | null;
          id: string;
          is_active: boolean;
          label: string | null;
          start_day: number;
          start_month: number;
          updated_at: string;
        };
        Insert: {
          created_at?: string;
          deleted_at?: string | null;
          deleted_by?: string | null;
          id?: string;
          is_active?: boolean;
          label?: string | null;
          start_day?: number;
          start_month: number;
          updated_at?: string;
        };
        Update: {
          created_at?: string;
          deleted_at?: string | null;
          deleted_by?: string | null;
          id?: string;
          is_active?: boolean;
          label?: string | null;
          start_day?: number;
          start_month?: number;
          updated_at?: string;
        };
        Relationships: [];
      };
      income_records: {
        Row: {
          amount: number;
          amount_base: number;
          created_at: string;
          created_by: string;
          currency: string;
          date: string;
          deleted_at: string | null;
          deleted_by: string | null;
          exchange_rate_used: number;
          id: string;
          income_source: string;
          notes: string | null;
          property_id: string;
          room_id: string | null;
          status: string;
          updated_at: string;
          updated_by: string | null;
        };
        Insert: {
          amount: number;
          amount_base: number;
          created_at?: string;
          created_by: string;
          currency: string;
          date: string;
          deleted_at?: string | null;
          deleted_by?: string | null;
          exchange_rate_used: number;
          id?: string;
          income_source: string;
          notes?: string | null;
          property_id: string;
          room_id?: string | null;
          status?: string;
          updated_at?: string;
          updated_by?: string | null;
        };
        Update: {
          amount?: number;
          amount_base?: number;
          created_at?: string;
          created_by?: string;
          currency?: string;
          date?: string;
          deleted_at?: string | null;
          deleted_by?: string | null;
          exchange_rate_used?: number;
          id?: string;
          income_source?: string;
          notes?: string | null;
          property_id?: string;
          room_id?: string | null;
          status?: string;
          updated_at?: string;
          updated_by?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: 'income_records_property_id_fkey';
            columns: ['property_id'];
            isOneToOne: false;
            referencedRelation: 'properties';
            referencedColumns: ['id'];
          },
        ];
      };
      notifications: {
        Row: {
          body: string | null;
          created_at: string;
          deleted_at: string | null;
          deleted_by: string | null;
          id: string;
          is_read: boolean;
          read_at: string | null;
          related_entity_id: string | null;
          related_entity_type: string | null;
          title: string;
          type: string;
          user_id: string;
        };
        Insert: {
          body?: string | null;
          created_at?: string;
          deleted_at?: string | null;
          deleted_by?: string | null;
          id?: string;
          is_read?: boolean;
          read_at?: string | null;
          related_entity_id?: string | null;
          related_entity_type?: string | null;
          title: string;
          type: string;
          user_id: string;
        };
        Update: {
          body?: string | null;
          created_at?: string;
          deleted_at?: string | null;
          deleted_by?: string | null;
          id?: string;
          is_read?: boolean;
          read_at?: string | null;
          related_entity_id?: string | null;
          related_entity_type?: string | null;
          title?: string;
          type?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'notifications_user_id_fkey';
            columns: ['user_id'];
            isOneToOne: false;
            referencedRelation: 'user_profiles';
            referencedColumns: ['id'];
          },
        ];
      };
      properties: {
        Row: {
          address: string | null;
          base_currency: string;
          country_id: string;
          created_at: string;
          deleted_at: string | null;
          deleted_by: string | null;
          id: string;
          is_active: boolean;
          name: string;
          updated_at: string;
        };
        Insert: {
          address?: string | null;
          base_currency: string;
          country_id: string;
          created_at?: string;
          deleted_at?: string | null;
          deleted_by?: string | null;
          id?: string;
          is_active?: boolean;
          name: string;
          updated_at?: string;
        };
        Update: {
          address?: string | null;
          base_currency?: string;
          country_id?: string;
          created_at?: string;
          deleted_at?: string | null;
          deleted_by?: string | null;
          id?: string;
          is_active?: boolean;
          name?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'properties_country_id_fkey';
            columns: ['country_id'];
            isOneToOne: false;
            referencedRelation: 'countries';
            referencedColumns: ['id'];
          },
        ];
      };
      property_assignments: {
        Row: {
          assigned_at: string;
          assigned_by: string;
          deleted_at: string | null;
          deleted_by: string | null;
          id: string;
          property_id: string;
          user_id: string;
        };
        Insert: {
          assigned_at?: string;
          assigned_by: string;
          deleted_at?: string | null;
          deleted_by?: string | null;
          id?: string;
          property_id: string;
          user_id: string;
        };
        Update: {
          assigned_at?: string;
          assigned_by?: string;
          deleted_at?: string | null;
          deleted_by?: string | null;
          id?: string;
          property_id?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'property_assignments_property_id_fkey';
            columns: ['property_id'];
            isOneToOne: false;
            referencedRelation: 'properties';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'property_assignments_user_id_fkey';
            columns: ['user_id'];
            isOneToOne: false;
            referencedRelation: 'user_profiles';
            referencedColumns: ['id'];
          },
        ];
      };
      recurring_expenses: {
        Row: {
          amount: number;
          category_id: string;
          created_at: string;
          created_by: string;
          currency: string;
          day_of_month: number | null;
          deleted_at: string | null;
          deleted_by: string | null;
          end_date: string | null;
          id: string;
          is_active: boolean;
          next_due_date: string;
          notes: string | null;
          payment_method: string;
          property_id: string;
          recurrence_type: string;
          room_id: string | null;
          start_date: string;
          updated_at: string;
          vendor: string | null;
        };
        Insert: {
          amount: number;
          category_id: string;
          created_at?: string;
          created_by: string;
          currency: string;
          day_of_month?: number | null;
          deleted_at?: string | null;
          deleted_by?: string | null;
          end_date?: string | null;
          id?: string;
          is_active?: boolean;
          next_due_date: string;
          notes?: string | null;
          payment_method: string;
          property_id: string;
          recurrence_type: string;
          room_id?: string | null;
          start_date: string;
          updated_at?: string;
          vendor?: string | null;
        };
        Update: {
          amount?: number;
          category_id?: string;
          created_at?: string;
          created_by?: string;
          currency?: string;
          day_of_month?: number | null;
          deleted_at?: string | null;
          deleted_by?: string | null;
          end_date?: string | null;
          id?: string;
          is_active?: boolean;
          next_due_date?: string;
          notes?: string | null;
          payment_method?: string;
          property_id?: string;
          recurrence_type?: string;
          room_id?: string | null;
          start_date?: string;
          updated_at?: string;
          vendor?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: 'recurring_expenses_property_id_fkey';
            columns: ['property_id'];
            isOneToOne: false;
            referencedRelation: 'properties';
            referencedColumns: ['id'];
          },
        ];
      };
      report_history: {
        Row: {
          country_ids: string[] | null;
          created_at: string;
          date_from: string;
          date_to: string;
          deleted_at: string | null;
          deleted_by: string | null;
          file_size_kb: number | null;
          file_url: string;
          format: string;
          generated_by: string;
          id: string;
          manager_ids: string[] | null;
          property_ids: string[] | null;
          report_type: string;
          status: string;
        };
        Insert: {
          country_ids?: string[] | null;
          created_at?: string;
          date_from: string;
          date_to: string;
          deleted_at?: string | null;
          deleted_by?: string | null;
          file_size_kb?: number | null;
          file_url: string;
          format: string;
          generated_by: string;
          id?: string;
          manager_ids?: string[] | null;
          property_ids?: string[] | null;
          report_type: string;
          status?: string;
        };
        Update: {
          country_ids?: string[] | null;
          created_at?: string;
          date_from?: string;
          date_to?: string;
          deleted_at?: string | null;
          deleted_by?: string | null;
          file_size_kb?: number | null;
          file_url?: string;
          format?: string;
          generated_by?: string;
          id?: string;
          manager_ids?: string[] | null;
          property_ids?: string[] | null;
          report_type?: string;
          status?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'report_history_generated_by_fkey';
            columns: ['generated_by'];
            isOneToOne: false;
            referencedRelation: 'user_profiles';
            referencedColumns: ['id'];
          },
        ];
      };
      rooms: {
        Row: {
          created_at: string;
          deleted_at: string | null;
          deleted_by: string | null;
          description: string | null;
          id: string;
          is_active: boolean;
          name: string;
          property_id: string;
          updated_at: string;
        };
        Insert: {
          created_at?: string;
          deleted_at?: string | null;
          deleted_by?: string | null;
          description?: string | null;
          id?: string;
          is_active?: boolean;
          name: string;
          property_id: string;
          updated_at?: string;
        };
        Update: {
          created_at?: string;
          deleted_at?: string | null;
          deleted_by?: string | null;
          description?: string | null;
          id?: string;
          is_active?: boolean;
          name?: string;
          property_id?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'rooms_property_id_fkey';
            columns: ['property_id'];
            isOneToOne: false;
            referencedRelation: 'properties';
            referencedColumns: ['id'];
          },
        ];
      };
      user_profiles: {
        Row: {
          created_at: string;
          deleted_at: string | null;
          deleted_by: string | null;
          full_name: string;
          id: string;
          is_active: boolean;
          role: string;
          updated_at: string;
        };
        Insert: {
          created_at?: string;
          deleted_at?: string | null;
          deleted_by?: string | null;
          full_name: string;
          id: string;
          is_active?: boolean;
          role?: string;
          updated_at?: string;
        };
        Update: {
          created_at?: string;
          deleted_at?: string | null;
          deleted_by?: string | null;
          full_name?: string;
          id?: string;
          is_active?: boolean;
          role?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'user_profiles_deleted_by_fkey';
            columns: ['deleted_by'];
            isOneToOne: false;
            referencedRelation: 'user_profiles';
            referencedColumns: ['id'];
          },
        ];
      };
    };
    Views: {
      expense_summary_v: {
        Row: {
          base_currency: string | null;
          category_name: string | null;
          category_parent: string | null;
          country_id: string | null;
          country_name: string | null;
          month: string | null;
          original_currency: string | null;
          property_id: string | null;
          property_name: string | null;
          record_count: number | null;
          total_amount: number | null;
          total_amount_base: number | null;
          category_id: string | null;
        };
        Relationships: [];
      };
      pending_confirmations_v: {
        Row: {
          amount: number | null;
          amount_base: number | null;
          category_id: string | null;
          category_name: string | null;
          category_parent: string | null;
          created_at: string | null;
          currency: string | null;
          date: string | null;
          days_pending: number | null;
          id: string | null;
          property_id: string | null;
          property_name: string | null;
          recurring_id: string | null;
          room_id: string | null;
          room_name: string | null;
          vendor: string | null;
        };
        Relationships: [];
      };
      property_performance_v: {
        Row: {
          base_currency: string | null;
          country_id: string | null;
          country_name: string | null;
          net_profit_base: number | null;
          profit_margin_pct: number | null;
          property_id: string | null;
          property_name: string | null;
          total_expenses_base: number | null;
          total_revenue_base: number | null;
        };
        Relationships: [];
      };
      revenue_summary_v: {
        Row: {
          base_currency: string | null;
          country_id: string | null;
          country_name: string | null;
          income_source: string | null;
          month: string | null;
          original_currency: string | null;
          property_id: string | null;
          property_name: string | null;
          record_count: number | null;
          total_amount: number | null;
          total_amount_base: number | null;
        };
        Relationships: [];
      };
    };
    Functions: {
      get_my_property_ids: {
        Args: Record<PropertyKey, never>;
        Returns: string[];
      };
      get_my_role: {
        Args: Record<PropertyKey, never>;
        Returns: string;
      };
    };
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};

export type Tables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Row'];

export type TablesInsert<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Insert'];

export type TablesUpdate<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Update'];

export type Views<T extends keyof Database['public']['Views']> =
  Database['public']['Views'][T]['Row'];
